# Generated by Django 5.2 on 2026-06-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codice_fiscale',
            field=models.CharField(blank=True, default=None, help_text='Codice fiscale italiano (16 caratteri)', max_length=16, null=True, unique=True, verbose_name='Codice Fiscale'),
        ),
    ]
