# Generated by Django 5.2 on 2026-08-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_timbratura_data_ora_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='palette',
            field=models.CharField(choices=[('1', 'Blu'), ('2', 'Verde'), ('3', 'Marroncino'), ('4', 'Lavanda')], default='1', help_text="Schema colori dell'interfaccia, scelto liberamente da ogni utente", max_length=1, verbose_name='Palette colori'),
        ),
    ]
