# Generated by Django 5.2 on 2026-08-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accento2_role',
            field=models.CharField(choices=[('1', '1° colore'), ('2', '2° colore'), ('3', '3° colore'), ('4', '4° colore')], default='2', help_text='Quale colore usare per accenti secondari (badge, dettagli)', max_length=1, verbose_name='Colore accento secondario'),
        ),
        migrations.AddField(
            model_name='user',
            name='accento_role',
            field=models.CharField(choices=[('1', '1° colore'), ('2', '2° colore'), ('3', '3° colore'), ('4', '4° colore')], default='1', help_text='Quale colore usare per bottoni/link/accenti principali', max_length=1, verbose_name='Colore accento primario'),
        ),
        migrations.AddField(
            model_name='user',
            name='navbar_role',
            field=models.CharField(choices=[('1', '1° colore'), ('2', '2° colore'), ('3', '3° colore'), ('4', '4° colore')], default='1', help_text='Quale colore della palette scelta usare per la barra in alto', max_length=1, verbose_name='Colore navbar'),
        ),
        migrations.AddField(
            model_name='user',
            name='sidebar_role',
            field=models.CharField(choices=[('1', '1° colore'), ('2', '2° colore'), ('3', '3° colore'), ('4', '4° colore')], default='1', help_text='Quale colore della palette scelta usare per la sidebar', max_length=1, verbose_name='Colore sidebar'),
        ),
    ]
