# Generated by Django 5.2 on 2026-05-13 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCorrispondenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Corrispondenza',
                'verbose_name_plural': 'Tipi Corrispondenza',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Corrispondenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocollo', models.CharField(blank=True, help_text='Generato automaticamente: CORyyyyNNNN', max_length=20, unique=True, verbose_name='N. Protocollo')),
                ('oggetto', models.CharField(max_length=200, verbose_name='Oggetto')),
                ('contenuto', models.TextField(verbose_name='Contenuto')),
                ('data_invio', models.DateField(blank=True, null=True, verbose_name='Data Invio')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('inviata', 'Inviata'), ('archiviata', 'Archiviata')], default='bozza', max_length=20, verbose_name='Stato')),
                ('priorita', models.CharField(choices=[('bassa', 'Bassa'), ('normale', 'Normale'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normale', max_length=10, verbose_name='Priorità')),
                ('tipo_destinatario', models.CharField(choices=[('interno', 'Utente interno'), ('esterno', 'Destinatario esterno')], default='esterno', max_length=20, verbose_name='Tipo Destinatario')),
                ('destinatario_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome / Ragione Sociale')),
                ('destinatario_indirizzo', models.CharField(blank=True, max_length=200, verbose_name='Indirizzo')),
                ('destinatario_cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('destinatario_citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('destinatario_provincia', models.CharField(blank=True, max_length=5, verbose_name='Prov.')),
                ('destinatario_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Destinatario')),
                ('destinatario_telefono', models.CharField(blank=True, max_length=20, verbose_name='Tel.')),
                ('note_interne', models.TextField(blank=True, verbose_name='Note Interne')),
                ('allegato', models.FileField(blank=True, null=True, upload_to='corrispondenza/allegati/%Y/%m/', verbose_name='Allegato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrispondenze_create', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('destinatario_utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrispondenze_ricevute', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario (utente)')),
                ('tipo_corrispondenza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corrispondenza.tipocorrispondenza', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Corrispondenza',
                'verbose_name_plural': 'Corrispondenze',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all', 'Può visualizzare tutta la corrispondenza'), ('can_send', 'Può inviare corrispondenza')],
            },
        ),
    ]
