# Generated by Django 5.2 on 2026-05-13 00:59

import core.models_legacy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('data_inizio', models.DateTimeField(verbose_name='Data/ora inizio')),
                ('data_fine', models.DateTimeField(blank=True, null=True, verbose_name='Data/ora fine')),
                ('tutto_il_giorno', models.BooleanField(default=False, verbose_name='Tutto il giorno')),
                ('colore', models.CharField(choices=[('#007bff', 'Blu'), ('#28a745', 'Verde'), ('#dc3545', 'Rosso'), ('#ffc107', 'Giallo'), ('#17a2b8', 'Ciano'), ('#fd7e14', 'Arancione'), ('#6f42c1', 'Viola'), ('#6c757d', 'Grigio')], default='#007bff', max_length=7, verbose_name='Colore')),
                ('visibilita', models.CharField(choices=[('personale', 'Solo io'), ('aziendale', 'Tutti (aziendale)')], default='personale', max_length=20, verbose_name='Visibilità')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
            ],
            options={
                'verbose_name': 'Evento Calendario',
                'verbose_name_plural': 'Eventi Calendario',
                'ordering': ['data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='ModuloRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome modulo')),
                ('codice', models.SlugField(unique=True, verbose_name='Codice')),
                ('app_name', models.CharField(max_length=100, verbose_name='Nome app Django')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('categoria', models.CharField(choices=[('base', 'Base (obbligatorio)'), ('vendite', 'Vendite'), ('acquisti', 'Acquisti'), ('magazzino', 'Magazzino'), ('produzione', 'Produzione'), ('amministrazione', 'Amministrazione'), ('hr', 'Risorse Umane'), ('crm', 'CRM'), ('altro', 'Altro')], default='altro', max_length=50, verbose_name='Categoria')),
                ('attivo', models.BooleanField(default=False, verbose_name='Attivo')),
                ('obbligatorio', models.BooleanField(default=False, help_text='Moduli obbligatori non disattivabili', verbose_name='Obbligatorio')),
                ('versione', models.CharField(default='1.0.0', max_length=20, verbose_name='Versione')),
                ('dipendenze', models.JSONField(blank=True, default=list, help_text='Lista dei codici moduli richiesti', verbose_name='Dipendenze')),
                ('icona', models.CharField(blank=True, max_length=50, verbose_name='Icona Bootstrap')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine visualizzazione')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Moduli',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('nome', models.CharField(help_text="Es. 'Responsabile HR', 'Addetto Payroll'", max_length=100, unique=True, verbose_name='Nome Template')),
                ('descrizione', models.TextField(blank=True, help_text='Descrizione dei permessi inclusi in questo template', verbose_name='Descrizione')),
                ('permessi_base', models.JSONField(blank=True, default=list, help_text='Permessi operativi base (timbrature, ferie, etc.)', verbose_name='Permessi Base')),
                ('attivo', models.BooleanField(default=True, help_text='Se disattivato, il template non appare nelle selezioni', verbose_name='Attivo')),
                ('n_utilizzi', models.PositiveIntegerField(default=0, help_text='Quante volte questo template è stato applicato', verbose_name='Numero Utilizzi')),
            ],
            options={
                'verbose_name': 'Template Permessi',
                'verbose_name_plural': 'Template Permessi',
                'db_table': 'core_permission_template',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID oggetto')),
                ('qr_image', models.ImageField(upload_to=core.models_legacy.qrcode_upload_path, verbose_name='Immagine QR')),
                ('url', models.URLField(max_length=500, verbose_name='URL del QR Code')),
                ('size', models.PositiveIntegerField(default=300, verbose_name='Dimensione (px)')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID oggetto')),
                ('file', models.FileField(upload_to=core.models_legacy.allegato_upload_path, verbose_name='File')),
                ('nome_originale', models.CharField(blank=True, max_length=255, verbose_name='Nome file originale')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('dimensione', models.PositiveIntegerField(default=0, verbose_name='Dimensione (bytes)')),
                ('tipo_file', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo contenuto')),
            ],
            options={
                'verbose_name': 'Allegato',
                'verbose_name_plural': 'Allegati',
                'ordering': ['-created_at'],
            },
        ),
    ]
