# Generated by Django 5.2 on 2026-05-13 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allegato',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Caricato da'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='creato_da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_calendario', to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
        migrations.AddIndex(
            model_name='moduloregistry',
            index=models.Index(fields=['attivo'], name='core_modulo_attivo_edf406_idx'),
        ),
        migrations.AddIndex(
            model_name='moduloregistry',
            index=models.Index(fields=['categoria', 'attivo'], name='core_modulo_categor_aef4f4_idx'),
        ),
        migrations.AddField(
            model_name='permissiontemplate',
            name='permessi_crud',
            field=models.ManyToManyField(blank=True, help_text='Permessi CRUD sui modelli (add, view, change, delete)', limit_choices_to={'content_type__app_label__in': ['users', 'payroll', 'core']}, related_name='templates_crud', to='auth.permission', verbose_name='Permessi CRUD'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo contenuto'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
        migrations.AddIndex(
            model_name='allegato',
            index=models.Index(fields=['content_type', 'object_id'], name='core_allega_content_f28245_idx'),
        ),
        migrations.AddIndex(
            model_name='allegato',
            index=models.Index(fields=['created_at'], name='core_allega_created_d5614d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocalendario',
            index=models.Index(fields=['data_inizio', 'data_fine'], name='core_evento_data_in_d0b8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocalendario',
            index=models.Index(fields=['creato_da', 'visibilita'], name='core_evento_creato__847cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='permissiontemplate',
            index=models.Index(fields=['nome'], name='core_permis_nome_a743e5_idx'),
        ),
        migrations.AddIndex(
            model_name='permissiontemplate',
            index=models.Index(fields=['attivo'], name='core_permis_attivo_be47e2_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['content_type', 'object_id'], name='core_qrcode_content_db4129_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['created_at'], name='core_qrcode_created_d156a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qrcode',
            unique_together={('content_type', 'object_id')},
        ),
    ]
