# Generated by Django 5.2 on 2026-06-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontemplate',
            name='permessi_crud',
            field=models.ManyToManyField(blank=True, help_text='Permessi CRUD sui modelli (add, view, change, delete)', related_name='templates_crud', to='auth.permission', verbose_name='Permessi CRUD'),
        ),
        migrations.CreateModel(
            name='InvioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canale', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('entrambi', 'WhatsApp + Email')], max_length=10, verbose_name='Canale')),
                ('destinatario_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome destinatario')),
                ('telefono', models.CharField(blank=True, max_length=25, verbose_name='Telefono WA')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('oggetto', models.CharField(blank=True, max_length=255, verbose_name='Oggetto / titolo')),
                ('messaggio', models.TextField(blank=True, verbose_name='Messaggio')),
                ('ha_pdf', models.BooleanField(default=False, verbose_name='Con PDF allegato')),
                ('stato', models.CharField(choices=[('pending', 'In attesa'), ('inviato', 'Inviato'), ('errore', 'Errore')], default='pending', max_length=10, verbose_name='Stato')),
                ('errore_dettaglio', models.TextField(blank=True, verbose_name='Dettaglio errore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invii_log', to=settings.AUTH_USER_MODEL, verbose_name='Inviato da')),
            ],
            options={
                'verbose_name': 'Log invio',
                'verbose_name_plural': 'Log invii',
                'db_table': 'core_invia_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stato', 'canale'], name='core_invia__stato_0a7f4a_idx'), models.Index(fields=['utente', 'created_at'], name='core_invia__utente__ada1f3_idx')],
            },
        ),
    ]
