# Generated by Django 5.2 on 2026-06-29 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cespiti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAttrezzatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Tipo attrezzatura',
                'verbose_name_plural': 'Tipi attrezzatura',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AttrezzaturaAutomezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fissa', models.BooleanField(default=True, verbose_name='Fissa')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrezzature', to='cespiti.automezzo', verbose_name='Automezzo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attrezzature_automezzo', to='cespiti.tipoattrezzatura', verbose_name='Tipo attrezzatura')),
            ],
            options={
                'verbose_name': 'Attrezzatura automezzo',
                'verbose_name_plural': 'Attrezzature automezzo',
                'ordering': ['tipo__nome'],
                'unique_together': {('automezzo', 'tipo')},
            },
        ),
    ]
