# Generated by Django 5.2 on 2026-08-26, mano modificata: state-only.
# Il cluster automezzi (Automezzo/Manutenzione/AllegatoManutenzione/
# Rifornimento/EventoAutomezzo) e' stato spostato nell'app automezzi
# (vedi automezzi/migrations/0001_initial.py) e TipoAttrezzatura/
# AttrezzaturaAutomezzo in magazzino (vedi magazzino/migrations/0014_...).
# Qui aggiorniamo solo lo STATE di cespiti: nessuna scrittura sul DB.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cespiti', '0002_attrezzatura_automezzo'),
        ('magazzino', '0014_tipoattrezzatura_alter_caricocisterna_mezzo_and_more'),
        ('servizi', '0028_alter_distinta_mezzo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='attrezzaturaautomezzo',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='attrezzaturaautomezzo',
                    name='automezzo',
                ),
                migrations.RemoveField(
                    model_name='attrezzaturaautomezzo',
                    name='tipo',
                ),
                migrations.RemoveField(
                    model_name='automezzo',
                    name='assegnato_a',
                ),
                migrations.RemoveField(
                    model_name='rifornimento',
                    name='automezzo',
                ),
                migrations.RemoveField(
                    model_name='eventoautomezzo',
                    name='automezzo',
                ),
                migrations.RemoveField(
                    model_name='manutenzione',
                    name='automezzo',
                ),
                migrations.RemoveField(
                    model_name='eventoautomezzo',
                    name='dipendente_coinvolto',
                ),
                migrations.RemoveField(
                    model_name='manutenzione',
                    name='fornitore',
                ),
                migrations.RemoveField(
                    model_name='manutenzione',
                    name='responsabile',
                ),
                migrations.RemoveField(
                    model_name='manutenzione',
                    name='seguito_da',
                ),
                migrations.DeleteModel(
                    name='AllegatoManutenzione',
                ),
                migrations.DeleteModel(
                    name='AttrezzaturaAutomezzo',
                ),
                migrations.DeleteModel(
                    name='TipoAttrezzatura',
                ),
                migrations.DeleteModel(
                    name='Rifornimento',
                ),
                migrations.DeleteModel(
                    name='Automezzo',
                ),
                migrations.DeleteModel(
                    name='EventoAutomezzo',
                ),
                migrations.DeleteModel(
                    name='Manutenzione',
                ),
            ],
            database_operations=[],
        ),
    ]
