# Generated by Django 5.2 on 2026-08-26, mano modificata: state-only.
# Il cluster stabilimenti (Stabilimento/CostiStabilimento/DocStabilimento)
# e' stato spostato nell'app stabilimenti (vedi
# stabilimenti/migrations/0001_initial.py). Qui aggiorniamo solo lo STATE
# di cespiti: nessuna scrittura sul DB. Con questa migrazione cespiti non
# ha piu' nessun modello — resta in INSTALLED_APPS solo come ancora
# storica per le migrazioni di automezzi/magazzino/servizi/stabilimenti.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cespiti', '0003_remove_automezzi_cluster'),
        ('magazzino', '0015_alter_caricomezzo_stabilimento_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='docstabilimento',
                    name='caricato_da',
                ),
                migrations.RemoveField(
                    model_name='docstabilimento',
                    name='stabilimento',
                ),
                migrations.RemoveField(
                    model_name='stabilimento',
                    name='creato_da',
                ),
                migrations.RemoveField(
                    model_name='stabilimento',
                    name='modificato_da',
                ),
                migrations.RemoveField(
                    model_name='stabilimento',
                    name='responsabile_amministrativo',
                ),
                migrations.RemoveField(
                    model_name='stabilimento',
                    name='responsabile_operativo',
                ),
                migrations.DeleteModel(
                    name='CostiStabilimento',
                ),
                migrations.DeleteModel(
                    name='DocStabilimento',
                ),
                migrations.DeleteModel(
                    name='Stabilimento',
                ),
            ],
            database_operations=[],
        ),
    ]
