# Generated by Django 5.2 on 2026-06-14 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0007_azienda_portal_user_azienda_utente_riferimento'),
        ('servizi', '0018_alter_condominiostabile_prezzo_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaDigitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_svg', models.TextField(verbose_name='Firma (base64 PNG)')),
                ('firmato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('firmato_da', models.CharField(blank=True, max_length=200, verbose_name='Nome firmatario')),
                ('ods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_digitale', to='servizi.ods')),
            ],
            options={
                'verbose_name': 'Firma digitale',
            },
        ),
        migrations.CreateModel(
            name='RichiestaIntervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(max_length=200, verbose_name='Tipo problema / infestante')),
                ('urgenza', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('emergenza', 'Emergenza')], default='normale', max_length=20)),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('data_preferita', models.DateField(blank=True, null=True, verbose_name='Data preferita')),
                ('creata_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('gestita', models.BooleanField(default=False, verbose_name='Presa in carico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_intervento', to='anagrafica.azienda')),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste_intervento', to='anagrafica.filiale', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Richiesta intervento',
                'verbose_name_plural': 'Richieste intervento',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='SegnalazioneInfestazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luogo', models.CharField(max_length=200, verbose_name='Luogo / area')),
                ('infestante', models.CharField(max_length=200, verbose_name='Infestante osservato')),
                ('note', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='segnalazioni/')),
                ('creata_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni', to='anagrafica.azienda')),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segnalazioni', to='anagrafica.filiale', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Segnalazione infestazione',
                'verbose_name_plural': 'Segnalazioni infestazione',
                'ordering': ['-creata_il'],
            },
        ),
    ]
