# Generated by Django 5.2 on 2026-08-26 08:50, mano modificata il 26/08/2026:
# spostamento di un modello Django tra due app senza perdere dati.
# SeparateDatabaseAndState: la STATE dice a Django "questi modelli ora
# vivono qui" senza toccare il DB; le RunSQL rinominano le tabelle reali
# (create originariamente da cespiti/migrations/0001_initial.py e
# 0002_attrezzatura_automezzo.py) cosi' i dati esistenti sopravvivono.
# Vedi ~/.claude/plans (standardizzazione automezzi/stabilimenti, 26/08/2026).

import automezzi.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0009_filiale_latitudine_filiale_longitudine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cespiti', '0002_attrezzatura_automezzo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Automezzo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('numero_mezzo', models.IntegerField(blank=True, null=True)),
                        ('targa', models.CharField(max_length=10, unique=True)),
                        ('marca', models.CharField(max_length=50)),
                        ('modello', models.CharField(max_length=50)),
                        ('anno_immatricolazione', models.PositiveIntegerField()),
                        ('chilometri_attuali', models.PositiveIntegerField(default=0)),
                        ('attivo', models.BooleanField(default=True)),
                        ('disponibile', models.BooleanField(default=True)),
                        ('bloccata', models.BooleanField(default=False)),
                        ('motivo_blocco', models.TextField(blank=True, null=True)),
                        ('libretto_fronte', models.FileField(blank=True, null=True, upload_to=automezzi.models.libretto_upload_path)),
                        ('libretto_retro', models.FileField(blank=True, null=True, upload_to=automezzi.models.libretto_upload_path)),
                        ('assicurazione', models.FileField(blank=True, null=True, upload_to=automezzi.models.assicurazione_upload_path)),
                        ('data_revisione', models.DateField(blank=True, null=True)),
                        ('data_scadenza_assicurazione', models.DateField(blank=True, null=True)),
                        ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automezzi_assegnati', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Automezzo',
                        'verbose_name_plural': 'Automezzi',
                        'ordering': ['targa'],
                    },
                ),
                migrations.CreateModel(
                    name='EventoAutomezzo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tipo', models.CharField(choices=[('incidente', 'Incidente'), ('furto', 'Furto'), ('fermo', 'Fermo amministrativo'), ('guasto', 'Guasto/avaria'), ('altro', 'Altro')], max_length=20)),
                        ('data_evento', models.DateField()),
                        ('descrizione', models.TextField(blank=True)),
                        ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                        ('file_allegato', models.FileField(blank=True, null=True, upload_to=automezzi.models.allegato_evento_path)),
                        ('risolto', models.BooleanField(default=False)),
                        ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='automezzi.automezzo')),
                        ('dipendente_coinvolto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automezzi_eventi_coinvolto', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Evento Automezzo',
                        'verbose_name_plural': 'Eventi Automezzo',
                        'ordering': ['-data_evento'],
                    },
                ),
                migrations.CreateModel(
                    name='Manutenzione',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('data_apertura', models.DateTimeField(auto_now_add=True, null=True)),
                        ('data_prevista', models.DateField(null=True)),
                        ('descrizione', models.CharField(max_length=255)),
                        ('stato', models.CharField(choices=[('aperta', 'Manutenzione Aperta'), ('in_corso', 'In Corso'), ('terminata', 'Terminata')], default='aperta', max_length=10)),
                        ('luogo', models.CharField(blank=True, max_length=200)),
                        ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                        ('allegati', models.FileField(blank=True, null=True, upload_to=automezzi.models.allegati_manutenzione_path)),
                        ('data_inizio_manutenzione', models.DateTimeField(blank=True, null=True)),
                        ('km_consegna', models.PositiveIntegerField(blank=True, null=True)),
                        ('foglio_accettazione', models.FileField(blank=True, null=True, upload_to=automezzi.models.allegati_manutenzione_path)),
                        ('note_responsabile', models.TextField(blank=True)),
                        ('note_finali', models.TextField(blank=True)),
                        ('fattura_fornitore', models.FileField(blank=True, null=True, upload_to=automezzi.models.allegati_manutenzione_path)),
                        ('data_completamento', models.DateTimeField(blank=True, null=True)),
                        ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutenzioni', to='automezzi.automezzo')),
                        ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automezzi_manutenzioni', to='anagrafica.fornitore')),
                        ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automezzi_manutenzioni_responsabile', to=settings.AUTH_USER_MODEL)),
                        ('seguito_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automezzi_manutenzioni_seguite', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Manutenzione',
                        'verbose_name_plural': 'Manutenzioni',
                        'ordering': ['-data_prevista'],
                    },
                ),
                migrations.CreateModel(
                    name='AllegatoManutenzione',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(max_length=200)),
                        ('file', models.FileField(upload_to=automezzi.models.allegati_manutenzione_path)),
                        ('data_upload', models.DateTimeField(auto_now_add=True)),
                        ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('manutenzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati_aggiuntivi', to='automezzi.manutenzione')),
                    ],
                    options={
                        'verbose_name': 'Allegato Manutenzione',
                        'verbose_name_plural': 'Allegati Manutenzione',
                        'ordering': ['-data_upload'],
                    },
                ),
                migrations.CreateModel(
                    name='Rifornimento',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('data', models.DateField()),
                        ('litri', models.DecimalField(decimal_places=2, max_digits=6)),
                        ('costo_totale', models.DecimalField(decimal_places=2, max_digits=7)),
                        ('chilometri', models.PositiveIntegerField()),
                        ('scontrino', models.FileField(blank=True, null=True, upload_to=automezzi.models.scontrino_upload_path)),
                        ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifornimenti', to='automezzi.automezzo')),
                    ],
                    options={
                        'verbose_name': 'Rifornimento',
                        'verbose_name_plural': 'Rifornimenti',
                        'ordering': ['-data'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_automezzo RENAME TO automezzi_automezzo;",
                    reverse_sql="ALTER TABLE automezzi_automezzo RENAME TO cespiti_automezzo;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_eventoautomezzo RENAME TO automezzi_eventoautomezzo;",
                    reverse_sql="ALTER TABLE automezzi_eventoautomezzo RENAME TO cespiti_eventoautomezzo;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_manutenzione RENAME TO automezzi_manutenzione;",
                    reverse_sql="ALTER TABLE automezzi_manutenzione RENAME TO cespiti_manutenzione;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_allegatomanutenzione RENAME TO automezzi_allegatomanutenzione;",
                    reverse_sql="ALTER TABLE automezzi_allegatomanutenzione RENAME TO cespiti_allegatomanutenzione;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_rifornimento RENAME TO automezzi_rifornimento;",
                    reverse_sql="ALTER TABLE automezzi_rifornimento RENAME TO cespiti_rifornimento;",
                ),
            ],
        ),
    ]
