# Generated by Django 5.2 on 2026-07-02 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisti', '0005_riga_ordine_iva'),
        ('fatturazione_attiva', '0003_notacredito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContoContabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome conto')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornitore', 'Fornitore'), ('cassa', 'Cassa'), ('banca', 'Banca'), ('generico', 'Generico')], max_length=20, verbose_name='Tipo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione / note')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conto Contabile',
                'verbose_name_plural': 'Conti Contabili',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoPrimaNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('causale', models.CharField(max_length=300, verbose_name='Causale')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importo (€)')),
                ('tipo', models.CharField(choices=[('fattura_cliente', 'Fattura cliente'), ('fattura_fornitore', 'Fattura fornitore'), ('incasso', 'Incasso da cliente'), ('pagamento', 'Pagamento a fornitore'), ('giroconto', 'Giroconto cassa/banca'), ('stipendi', 'Pagamento stipendi'), ('altro', 'Altro')], max_length=30, verbose_name='Tipo')),
                ('numero_documento', models.CharField(blank=True, max_length=100, verbose_name='N° documento')),
                ('is_automatico', models.BooleanField(default=False, verbose_name='Generato automaticamente')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conto_avere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_avere', to='contabilita.contocontabile', verbose_name='Conto Avere')),
                ('conto_dare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_dare', to='contabilita.contocontabile', verbose_name='Conto Dare')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_prima_nota_creati', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('fattura_attiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_prima_nota', to='fatturazione_attiva.fattura', verbose_name='Fattura cliente')),
                ('fattura_passiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_prima_nota', to='acquisti.fatturapassiva', verbose_name='Fattura fornitore')),
            ],
            options={
                'verbose_name': 'Movimento Prima Nota',
                'verbose_name_plural': 'Movimenti Prima Nota',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
