# Generated by Django 5.2 on 2026-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contocontabile',
            name='iban',
            field=models.CharField(blank=True, help_text='Solo per conti di tipo Banca', max_length=34, verbose_name='IBAN'),
        ),
    ]
