# Generated by Django 5.2 on 2026-08-11 16:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0002_contocontabile_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoprimanota',
            name='storna',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storno', to='contabilita.movimentoprimanota', verbose_name='Storna il movimento'),
        ),
        migrations.AlterField(
            model_name='movimentoprimanota',
            name='importo',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo (€)'),
        ),
    ]
