# Generated by Django 5.2 on 2026-08-12 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0003_movimentoprimanota_storna_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoprimanota',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='ImpostazioniContabilita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiusa_fino_al', models.DateField(blank=True, help_text='Nessun movimento potrà avere una data pari o precedente a questa. Lascia vuoto per non chiudere niente.', null=True, verbose_name='Contabilità chiusa fino al')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggiornata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aggiornata da')),
            ],
            options={
                'verbose_name': 'Impostazioni Contabilità',
                'verbose_name_plural': 'Impostazioni Contabilità',
            },
        ),
    ]
