# Generated by Django 5.2 on 2026-08-12 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisti', '0006_fatturapassiva_importo_pagato'),
        ('contabilita', '0004_alter_movimentoprimanota_data_and_more'),
        ('fatturazione_attiva', '0005_incassato_fatture_pagate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoprimanota',
            name='anno',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Anno'),
        ),
        migrations.AddField(
            model_name='movimentoprimanota',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='N° movimento'),
        ),
        migrations.AddField(
            model_name='movimentoprimanota',
            name='progressivo',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Progressivo'),
        ),
        migrations.AddConstraint(
            model_name='movimentoprimanota',
            constraint=models.UniqueConstraint(fields=('anno', 'progressivo'), name='movimento_progressivo_unico_per_anno'),
        ),
    ]
