# Generated by Django 5.2 on 2026-09-14 14:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0007_recupera_scritture_fatture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensile', 'Mensile'), ('trimestrale_opzione', 'Trimestrale per opzione (+1% interessi)'), ('trimestrale_naturale', 'Trimestrale naturale (senza interessi)')], max_length=25, verbose_name='Regime IVA')),
                ('valido_dal', models.DateField(verbose_name='Valido dal')),
                ('valido_al', models.DateField(blank=True, help_text='Lascia vuoto se è il regime tuttora in vigore.', null=True, verbose_name='Valido fino al')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regime IVA',
                'verbose_name_plural': 'Storico regimi IVA',
                'ordering': ['-valido_dal'],
            },
        ),
        migrations.AlterField(
            model_name='contocontabile',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fornitore', 'Fornitore'), ('cassa', 'Cassa'), ('banca', 'Banca'), ('iva_credito', 'IVA a credito'), ('iva_debito', 'IVA a debito'), ('generico', 'Generico')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='movimentoprimanota',
            name='tipo',
            field=models.CharField(choices=[('fattura_cliente', 'Fattura cliente'), ('nota_credito_cliente', 'Nota di credito a cliente'), ('fattura_fornitore', 'Fattura fornitore'), ('incasso', 'Incasso da cliente'), ('pagamento', 'Pagamento a fornitore'), ('giroconto', 'Giroconto cassa/banca'), ('stipendi', 'Pagamento stipendi'), ('altro', 'Altro')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='LiquidazioneIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicita', models.CharField(choices=[('mese', 'Mensile'), ('trimestre', 'Trimestrale')], max_length=10, verbose_name='Periodicità')),
                ('anno', models.PositiveSmallIntegerField(verbose_name='Anno')),
                ('periodo', models.PositiveSmallIntegerField(help_text='Mese (1-12) se mensile, trimestre (1-4) se trimestrale.', verbose_name='Periodo')),
                ('iva_a_debito', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA a debito del periodo')),
                ('iva_a_credito', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA a credito del periodo')),
                ('credito_precedente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Credito riportato dal periodo precedente')),
                ('interessi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Interessi (1% trimestrale per opzione)')),
                ('stato', models.CharField(choices=[('da_versare', 'Da versare'), ('versata', 'Versata')], default='da_versare', max_length=15, verbose_name='Stato')),
                ('data_versamento', models.DateField(blank=True, null=True, verbose_name='Data versamento')),
                ('riferimento_pagamento', models.CharField(blank=True, help_text='Es. quietanza F24, CRO del bonifico.', max_length=100, verbose_name='Riferimento pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creata da')),
            ],
            options={
                'verbose_name': 'Liquidazione IVA',
                'verbose_name_plural': 'Liquidazioni IVA',
                'ordering': ['-anno', '-periodo'],
            },
        ),
        migrations.AddField(
            model_name='movimentoprimanota',
            name='liquidazione_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='contabilita.liquidazioneiva', verbose_name='Liquidazione IVA'),
        ),
        migrations.AddConstraint(
            model_name='liquidazioneiva',
            constraint=models.UniqueConstraint(fields=('periodicita', 'anno', 'periodo'), name='contabilita_liquidazione_iva_unica_per_periodo'),
        ),
    ]
