# Generated by Django 5.2 on 2026-09-15 19:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0008_regimeiva_alter_contocontabile_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contocontabile',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fornitore', 'Fornitore'), ('cassa', 'Cassa'), ('banca', 'Banca'), ('custodia', 'Custodia (persona)'), ('iva_credito', 'IVA a credito'), ('iva_debito', 'IVA a debito'), ('generico', 'Generico')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PassaggioCassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo (€)')),
                ('forma', models.CharField(choices=[('contanti', 'Contanti'), ('assegno', 'Assegno')], default='contanti', max_length=10, verbose_name='Forma')),
                ('causale', models.CharField(max_length=300, verbose_name='Causale')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('a_conto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passaggi_ricevuti', to='contabilita.contocontabile', verbose_name='Chi riceve')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passaggi_cassa_creati', to=settings.AUTH_USER_MODEL, verbose_name='Registrato da')),
                ('da_conto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passaggi_consegnati', to='contabilita.contocontabile', verbose_name='Chi consegna')),
                ('movimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passaggio_cassa', to='contabilita.movimentoprimanota', verbose_name='Movimento generato')),
            ],
            options={
                'verbose_name': 'Passaggio di cassa',
                'verbose_name_plural': 'Passaggi di cassa',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
