# Generated by Django 5.2 on 2026-09-15 22:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0010_backfill_conti_custodia_utenti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passaggiocassa',
            name='forma',
        ),
        migrations.RemoveField(
            model_name='passaggiocassa',
            name='importo',
        ),
        migrations.RemoveField(
            model_name='passaggiocassa',
            name='movimento',
        ),
        migrations.AddField(
            model_name='contocontabile',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conto_custodia', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AddField(
            model_name='movimentoprimanota',
            name='forma',
            field=models.CharField(blank=True, choices=[('contanti', 'Contanti'), ('assegno', 'Assegno')], max_length=10, verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='movimentoprimanota',
            name='passaggio_cassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_prima_nota', to='contabilita.passaggiocassa', verbose_name='Passaggio di cassa'),
        ),
        migrations.AddField(
            model_name='passaggiocassa',
            name='confermato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passaggi_cassa_confermati', to=settings.AUTH_USER_MODEL, verbose_name='Confermato da'),
        ),
        migrations.AddField(
            model_name='passaggiocassa',
            name='confermato_il',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confermato il'),
        ),
        migrations.AddField(
            model_name='passaggiocassa',
            name='importo_assegno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo in assegni (€)'),
        ),
        migrations.AddField(
            model_name='passaggiocassa',
            name='importo_contanti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo in contanti (€)'),
        ),
    ]
