# Generated by Django 5.2 on 2026-09-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0012_backfill_utente_conti_custodia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentoprimanota',
            name='forma',
        ),
        migrations.RemoveField(
            model_name='movimentoprimanota',
            name='passaggio_cassa',
        ),
    ]
