# Generated by Django 5.1.4 on 2026-01-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fornitore",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
