# Generated by Django 5.1.4 on 2026-04-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0004_alter_cliente_id_alter_fornitore_id"),
        ("rappresentanti", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="rappresentante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clienti",
                to="rappresentanti.rappresentante",
                verbose_name="Rappresentante di competenza",
            ),
        ),
    ]
