# Generated by Django 5.1.4 on 2026-04-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0005_cliente_rappresentante"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="provincia",
            field=models.CharField(
                blank=True,
                help_text="Es: MI, RM, PA",
                max_length=5,
                verbose_name="Provincia (sigla)",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="regione",
            field=models.CharField(blank=True, max_length=100, verbose_name="Regione"),
        ),
        migrations.AddField(
            model_name="fornitore",
            name="provincia",
            field=models.CharField(
                blank=True,
                help_text="Es: MI, RM, PA",
                max_length=5,
                verbose_name="Provincia (sigla)",
            ),
        ),
        migrations.AddField(
            model_name="fornitore",
            name="regione",
            field=models.CharField(blank=True, max_length=100, verbose_name="Regione"),
        ),
    ]
