# Generated by Django 5.2 on 2026-05-13 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome CCNL')),
                ('tipo', models.CharField(choices=[('METALMECCANICI', 'Metalmeccanici'), ('COMMERCIO', 'Commercio e Terziario'), ('EDILIZIA', 'Edilizia'), ('CHIMICI', 'Chimici'), ('TRASPORTI', 'Trasporti e Logistica'), ('PUBBLICO_IMPIEGO', 'Pubblico Impiego'), ('SANITA', 'Sanità Privata'), ('TURISMO', 'Turismo e Pubblici Esercizi'), ('ALTRO', 'Altro')], max_length=50, verbose_name='Tipo')),
                ('data_inizio_validita', models.DateField(verbose_name='Data Inizio Validità')),
                ('data_fine_validita', models.DateField(blank=True, null=True, verbose_name='Data Fine Validità')),
                ('giorni_ferie_annui', models.IntegerField(default=26, help_text='4 settimane + 2 giorni', verbose_name='Giorni Ferie Annui')),
                ('ore_rol_annue', models.DecimalField(decimal_places=2, default=88, max_digits=6, verbose_name='Ore ROL Annue')),
                ('ore_permessi_retribuiti_annui', models.DecimalField(decimal_places=2, default=32, max_digits=6, verbose_name='Ore Permessi Retribuiti Annui')),
                ('percentuale_straordinario_feriale', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='% Straordinario Feriale')),
                ('percentuale_straordinario_festivo', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='% Straordinario Festivo')),
                ('percentuale_straordinario_notturno', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='% Straordinario Notturno')),
                ('ha_tredicesima', models.BooleanField(default=True, verbose_name='Ha Tredicesima')),
                ('ha_quattordicesima', models.BooleanField(default=False, verbose_name='Ha Quattordicesima')),
                ('maturazione_quattordicesima', models.CharField(blank=True, choices=[('GIUGNO', 'Giugno'), ('LUGLIO', 'Luglio'), ('DICEMBRE', 'Dicembre')], max_length=20, null=True, verbose_name='Maturazione Quattordicesima')),
                ('ha_scatti_anzianita', models.BooleanField(default=True, verbose_name='Ha Scatti Anzianità')),
                ('anni_per_scatto', models.IntegerField(default=2, verbose_name='Anni per Scatto')),
                ('importo_scatto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importo Scatto €')),
                ('numero_massimo_scatti', models.IntegerField(default=10, verbose_name='Numero Massimo Scatti')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'CCNL',
                'verbose_name_plural': 'CCNL',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BustaPaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.IntegerField(verbose_name='Mese')),
                ('anno', models.IntegerField(verbose_name='Anno')),
                ('data_elaborazione', models.DateField(auto_now_add=True, verbose_name='Data Elaborazione')),
                ('ore_ordinarie', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Ordinarie')),
                ('ore_straordinario_feriale', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Straordinario Feriale')),
                ('ore_straordinario_festivo', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Straordinario Festivo')),
                ('ore_straordinario_notturno', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Straordinario Notturno')),
                ('ore_ferie', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Ferie')),
                ('ore_rol', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore ROL')),
                ('ore_permessi', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Permessi')),
                ('ore_malattia', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Malattia')),
                ('imponibile_fiscale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Imponibile Fiscale €')),
                ('imponibile_contributivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Imponibile Contributivo €')),
                ('ritenute_previdenziali', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ritenute Previdenziali €')),
                ('ritenute_irpef', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ritenute IRPEF €')),
                ('addizionale_regionale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Addizionale Regionale €')),
                ('addizionale_comunale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Addizionale Comunale €')),
                ('altre_trattenute', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Altre Trattenute €')),
                ('detrazioni_fiscali', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Detrazioni Fiscali €')),
                ('netto_busta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Netto in Busta €')),
                ('tfr_maturato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TFR Maturato €')),
                ('confermata', models.BooleanField(default=False, verbose_name='Confermata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buste_paga', to=settings.AUTH_USER_MODEL, verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Busta Paga',
                'verbose_name_plural': 'Buste Paga',
                'ordering': ['-anno', '-mese', 'user'],
                'unique_together': {('user', 'mese', 'anno')},
            },
        ),
        migrations.CreateModel(
            name='LivelloInquadramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='es. 1, 2, 3 o A1, B2, etc.', max_length=20, verbose_name='Codice')),
                ('descrizione', models.CharField(help_text='es. Operaio generico, Impiegato di 3° livello', max_length=200, verbose_name='Descrizione')),
                ('paga_base_mensile', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paga Base Mensile €')),
                ('ore_settimanali_standard', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Ore Settimanali Standard')),
                ('ccnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livelli', to='payroll.ccnl', verbose_name='CCNL')),
            ],
            options={
                'verbose_name': 'Livello Inquadramento',
                'verbose_name_plural': 'Livelli Inquadramento',
                'ordering': ['ccnl', 'codice'],
                'unique_together': {('ccnl', 'codice')},
            },
        ),
        migrations.CreateModel(
            name='DatiContrattualiPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contratto', models.CharField(choices=[('TEMPO_INDETERMINATO', 'Tempo Indeterminato'), ('TEMPO_DETERMINATO', 'Tempo Determinato'), ('APPRENDISTATO', 'Apprendistato'), ('SOMMINISTRAZIONE', 'Somministrazione'), ('PART_TIME', 'Part Time')], default='TEMPO_INDETERMINATO', max_length=30, verbose_name='Tipo Contratto')),
                ('data_fine_contratto', models.DateField(blank=True, null=True, verbose_name='Data Fine Contratto')),
                ('data_cessazione', models.DateField(blank=True, null=True, verbose_name='Data Cessazione')),
                ('ore_settimanali', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Ore Settimanali')),
                ('percentuale_part_time', models.DecimalField(decimal_places=2, default=100, help_text='100 = full time', max_digits=5, verbose_name='% Part Time')),
                ('superminimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Superminimo €')),
                ('aliquota_addizionale_regionale', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Addizionale Regionale %')),
                ('aliquota_addizionale_comunale', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Addizionale Comunale %')),
                ('detrazione_lavoro_dipendente', models.BooleanField(default=True, verbose_name='Detrazione Lavoro Dipendente')),
                ('numero_figli_a_carico', models.IntegerField(default=0, verbose_name='Numero Figli a Carico')),
                ('coniuge_a_carico', models.BooleanField(default=False, verbose_name='Coniuge a Carico')),
                ('altri_familiari_a_carico', models.IntegerField(default=0, verbose_name='Altri Familiari a Carico')),
                ('iban', models.CharField(blank=True, max_length=27, verbose_name='IBAN')),
                ('ccnl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.ccnl', verbose_name='CCNL Applicato')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dati_payroll', to=settings.AUTH_USER_MODEL, verbose_name='Dipendente')),
                ('livello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.livelloinquadramento', verbose_name='Livello Inquadramento')),
            ],
            options={
                'verbose_name': 'Dati Contrattuali Payroll',
                'verbose_name_plural': 'Dati Contrattuali Payroll',
            },
        ),
        migrations.CreateModel(
            name='ManualePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(default='Manuale di Compilazione Form Payroll', max_length=200, verbose_name='Titolo')),
                ('contenuto', models.TextField(help_text='Contenuto del manuale in formato Markdown', verbose_name='Contenuto')),
                ('versione', models.CharField(default='1.0', max_length=20, verbose_name='Versione')),
                ('data_ultima_modifica', models.DateTimeField(auto_now=True, verbose_name='Data Ultima Modifica')),
                ('modificato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuali_modificati', to=settings.AUTH_USER_MODEL, verbose_name='Modificato Da')),
            ],
            options={
                'verbose_name': 'Manuale Payroll',
                'verbose_name_plural': 'Manuali Payroll',
                'ordering': ['-data_ultima_modifica'],
            },
        ),
        migrations.CreateModel(
            name='VoceBustaPaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPETENZA', 'Competenza'), ('TRATTENUTA', 'Trattenuta'), ('DEDUZIONE', 'Deduzione')], max_length=20, verbose_name='Tipo')),
                ('descrizione', models.CharField(max_length=200, verbose_name='Descrizione')),
                ('quantita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantità')),
                ('importo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importo Unitario €')),
                ('importo_totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo Totale €')),
                ('imponibile_fiscale', models.BooleanField(default=True, verbose_name='Imponibile Fiscale')),
                ('imponibile_contributivo', models.BooleanField(default=True, verbose_name='Imponibile Contributivo')),
                ('busta_paga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='payroll.bustapaga', verbose_name='Busta Paga')),
            ],
            options={
                'verbose_name': 'Voce Busta Paga',
                'verbose_name_plural': 'Voci Busta Paga',
                'ordering': ['busta_paga', 'tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ElementoRetributivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='es. Contingenza, EDR, Indennità turno', max_length=100, verbose_name='Nome')),
                ('codice', models.CharField(max_length=20, verbose_name='Codice')),
                ('tipo_calcolo', models.CharField(choices=[('FISSO', 'Importo Fisso'), ('PERCENTUALE_PAGA_BASE', 'Percentuale su Paga Base'), ('PERCENTUALE_RETRIBUZIONE', 'Percentuale su Retribuzione Totale'), ('ORARIO', 'Calcolato su Ore')], max_length=30, verbose_name='Tipo Calcolo')),
                ('valore', models.DecimalField(decimal_places=2, help_text='Importo fisso o percentuale', max_digits=10, verbose_name='Valore')),
                ('natura', models.CharField(choices=[('IMPONIBILE', 'Imponibile (fiscale e contributivo)'), ('NON_IMPONIBILE', 'Non Imponibile'), ('SOLO_FISCALE', 'Imponibile solo fiscale'), ('SOLO_CONTRIBUTIVO', 'Imponibile solo contributivo')], default='IMPONIBILE', max_length=20, verbose_name='Natura')),
                ('incluso_tfr', models.BooleanField(default=True, verbose_name='Incluso in TFR')),
                ('incluso_tredicesima', models.BooleanField(default=True, verbose_name='Incluso in Tredicesima')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('ccnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi_retributivi', to='payroll.ccnl', verbose_name='CCNL')),
            ],
            options={
                'verbose_name': 'Elemento Retributivo',
                'verbose_name_plural': 'Elementi Retributivi',
                'ordering': ['ccnl', 'codice'],
                'unique_together': {('ccnl', 'codice')},
            },
        ),
        migrations.CreateModel(
            name='FeriePermessiPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(verbose_name='Anno')),
                ('tipo', models.CharField(choices=[('FERIE', 'Ferie'), ('ROL', 'ROL/Permessi'), ('PERMESSO_RETRIBUITO', 'Permesso Retribuito'), ('PERMESSO_NON_RETRIBUITO', 'Permesso Non Retribuito'), ('MALATTIA', 'Malattia'), ('CONGEDO_PARENTALE', 'Congedo Parentale'), ('L104', 'Permesso L.104')], max_length=30, verbose_name='Tipo')),
                ('ore_maturate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Maturate')),
                ('ore_residuo_anno_precedente', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Residuo Anno Precedente')),
                ('ore_godute', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ore Godute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferie_permessi_payroll', to=settings.AUTH_USER_MODEL, verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Ferie/Permessi Payroll',
                'verbose_name_plural': 'Ferie/Permessi Payroll',
                'ordering': ['-anno', 'user'],
                'unique_together': {('user', 'anno', 'tipo')},
            },
        ),
    ]
