# Generated by Django 5.2 on 2026-05-30 02:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0004_privato_citta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome servizio')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('tariffa_cartello', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Prezzo di riferimento se non specificato nel contratto o nell'ODS", max_digits=10, verbose_name='Tariffa di cartello')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contratto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_default', models.DecimalField(decimal_places=2, help_text='Applicato a tutte le sedi; modificabile per singola sede', max_digits=10, verbose_name='Prezzo base')),
                ('periodicita', models.CharField(choices=[('mensile', 'Mensile'), ('bimestrale', 'Bimestrale'), ('trimestrale', 'Trimestrale'), ('semestrale', 'Semestrale'), ('annuale', 'Annuale'), ('a_chiamata', 'A chiamata')], default='mensile', max_length=20, verbose_name='Periodicità')),
                ('data_inizio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data inizio')),
                ('data_fine', models.DateField(blank=True, null=True, verbose_name='Data fine')),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('sospeso', 'Sospeso'), ('scaduto', 'Scaduto'), ('annullato', 'Annullato')], default='attivo', max_length=20, verbose_name='Stato')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratti', to='anagrafica.azienda', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratti_creati', to=settings.AUTH_USER_MODEL)),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratti', to='servizi.servizio', verbose_name='Servizio')),
            ],
            options={
                'verbose_name': 'Contratto',
                'verbose_name_plural': 'Contratti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContrattoFiliale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_override', models.DecimalField(blank=True, decimal_places=2, help_text='Lascia vuoto per usare il prezzo base del contratto', max_digits=10, null=True, verbose_name='Prezzo specifico sede')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Note sede')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiali_contratto', to='servizi.contratto')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratti_filiale', to='anagrafica.filiale')),
            ],
            options={
                'verbose_name': 'Sede contratto',
                'verbose_name_plural': 'Sedi contratto',
                'unique_together': {('contratto', 'filiale')},
            },
        ),
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-compilato dal contratto; modificabile manualmente', max_digits=10, null=True, verbose_name='Prezzo')),
                ('data_servizio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data servizio')),
                ('ora_inizio', models.TimeField(blank=True, null=True, verbose_name='Ora inizio')),
                ('ora_fine', models.TimeField(blank=True, null=True, verbose_name='Ora fine')),
                ('stato', models.CharField(choices=[('programmato', 'Programmato'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='programmato', max_length=20, verbose_name='Stato')),
                ('note_intervento', models.TextField(blank=True, verbose_name='Note intervento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contratto_filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ods', to='servizi.contrattofiliale', verbose_name='Contratto applicato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ods_creati', to=settings.AUTH_USER_MODEL)),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ods', to='anagrafica.filiale', verbose_name='Sede cliente')),
                ('privato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ods', to='anagrafica.privato', verbose_name='Cliente privato')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ods_assegnati', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ods', to='servizi.servizio', verbose_name='Servizio')),
            ],
            options={
                'verbose_name': 'Ordine di Servizio',
                'verbose_name_plural': 'Ordini di Servizio',
                'ordering': ['-data_servizio', '-created_at'],
            },
        ),
    ]
