# Generated by Django 5.2 on 2026-05-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='stato',
            field=models.CharField(choices=[('da_espletare', 'Da espletare'), ('programmato', 'Programmato'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='da_espletare', max_length=20, verbose_name='Stato'),
        ),
    ]
