# Generated by Django 5.2 on 2026-05-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0002_ods_stato_da_espletare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ods',
            name='data_incasso',
            field=models.DateField(blank=True, null=True, verbose_name='Data incasso'),
        ),
        migrations.AddField(
            model_name='ods',
            name='importo_incassato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importo incassato'),
        ),
        migrations.AddField(
            model_name='ods',
            name='incassato',
            field=models.BooleanField(default=False, verbose_name='Incassato'),
        ),
        migrations.AddField(
            model_name='ods',
            name='incasso_al_servizio',
            field=models.BooleanField(default=False, help_text='Il pagamento va riscosso al momento del servizio (non fatturato)', verbose_name='Incasso al servizio'),
        ),
    ]
