# Generated by Django 5.2 on 2026-05-31 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0003_ods_incasso_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ods',
            name='assistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ods_assistiti', to=settings.AUTH_USER_MODEL, verbose_name='Assistente'),
        ),
    ]
