# Generated by Django 5.2 on 2026-06-02 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0010_distinta_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinta',
            name='importo_ricevuto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Contante/pagamenti effettivamente ricevuti dal tecnico all'ufficio", max_digits=10, null=True, verbose_name='Importo ricevuto'),
        ),
        migrations.CreateModel(
            name='CondominioODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo servizio')),
                ('indirizzo', models.CharField(max_length=300, verbose_name='Indirizzo')),
                ('data', models.DateField(verbose_name='Data servizio')),
                ('ora', models.TimeField(blank=True, null=True, verbose_name='Ora')),
                ('prezzo_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo base per unità')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condomini_assistente', to=settings.AUTH_USER_MODEL, verbose_name='Assistente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condomini_creati', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condomini_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico')),
            ],
            options={
                'verbose_name': 'Condominio ODS',
                'verbose_name_plural': 'Condomini ODS',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RigaUnitaAbitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Intestatario')),
                ('servizio_effettuato', models.BooleanField(default=False, verbose_name='Servizio effettuato')),
                ('incasso_effettuato', models.BooleanField(default=False, verbose_name='Incasso effettuato')),
                ('importo_da_incassare', models.DecimalField(blank=True, decimal_places=2, help_text='Se vuoto usa il prezzo base del condominio', max_digits=10, null=True, verbose_name='Importo da incassare')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unita', to='servizi.condominioods')),
            ],
            options={
                'verbose_name': 'Unità abitativa',
                'verbose_name_plural': 'Unità abitative',
                'ordering': ['nome'],
            },
        ),
    ]
