# Generated by Django 5.2 on 2026-06-02 12:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0010_ricezione_mezzo'),
        ('servizi', '0011_condominioods'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominioods',
            name='distinta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condomini_set', to='servizi.distinta', verbose_name='Distinta'),
        ),
        migrations.AddField(
            model_name='condominioods',
            name='stato',
            field=models.CharField(choices=[('da_espletare', 'Da espletare'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='da_espletare', max_length=20, verbose_name='Stato'),
        ),
        migrations.CreateModel(
            name='RigaProdottoCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='Quantità')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='servizi.condominioods')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_condominio', to='magazzino.prodotto')),
            ],
            options={
                'verbose_name': 'Prodotto condominio',
                'verbose_name_plural': 'Prodotti condominio',
                'ordering': ['prodotto__nome_prodotto'],
            },
        ),
    ]
