# Generated by Django 5.2 on 2026-06-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0012_condominio_distinta_prodotti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratto',
            name='prezzo_default',
        ),
        migrations.RemoveField(
            model_name='contratto',
            name='servizio',
        ),
        migrations.RemoveField(
            model_name='contrattofiliale',
            name='prezzo_override',
        ),
        migrations.CreateModel(
            name='ContrattoRiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='servizi.contratto')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_contratto', to='servizi.servizio')),
            ],
            options={
                'verbose_name': 'Riga contratto',
                'verbose_name_plural': 'Righe contratto',
                'ordering': ['servizio__nome'],
                'unique_together': {('contratto', 'servizio')},
            },
        ),
    ]
