# Generated by Django 5.2 on 2026-06-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0013_contratto_righe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrattoFilialeRiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('contratto_filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe_sede', to='servizi.contrattofiliale')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_filiale_contratto', to='servizi.servizio')),
            ],
            options={
                'verbose_name': 'Riga sede contratto',
                'verbose_name_plural': 'Righe sede contratto',
                'ordering': ['servizio__nome'],
                'unique_together': {('contratto_filiale', 'servizio')},
            },
        ),
    ]
