# Generated by Django 5.2 on 2026-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0017_fix_ddl_stabile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiostabile',
            name='prezzo_base',
            field=models.DecimalField(decimal_places=2, help_text='Prezzo predefinito quando si crea un ODS da questo stabile', max_digits=10, verbose_name='Prezzo base per unità'),
        ),
        migrations.AlterField(
            model_name='unitaabitativabase',
            name='importo_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lascia vuoto per usare il prezzo base dello stabile', max_digits=10, null=True, verbose_name='Importo specifico'),
        ),
    ]
