# Generated by Django 5.2 on 2026-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0018_alter_condominiostabile_prezzo_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='stato',
            field=models.CharField(choices=[('da_espletare', 'Da espletare'), ('programmato', 'Programmato'), ('completato', 'Completato'), ('fatturato', 'Fatturato'), ('annullato', 'Annullato')], default='da_espletare', max_length=20, verbose_name='Stato'),
        ),
    ]
