# Generated by Django 5.2 on 2026-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0020_distinta_add_assistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='richiede_installazione',
            field=models.BooleanField(default=False, help_text='Se attivo, questo servizio prevede postazioni fisse da installare e monitorare', verbose_name='Richiede installazione'),
        ),
    ]
