# Generated by Django 5.2 on 2026-07-01 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0008_sede_unica'),
        ('servizi', '0021_add_richiede_installazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoServizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveSmallIntegerField(verbose_name='Anno')),
                ('frequenza', models.CharField(choices=[('mensile', 'Mensile (12/anno)'), ('bimestrale', 'Bimestrale (6/anno)'), ('trimestrale', 'Trimestrale (4/anno)'), ('semestrale', 'Semestrale (2/anno)'), ('annuale', 'Annuale (1/anno)')], max_length=20, verbose_name='Frequenza')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piani_servizio', to='anagrafica.azienda', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piani_creati', to=settings.AUTH_USER_MODEL)),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piani_servizio', to='anagrafica.filiale', verbose_name='Sede')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piani_servizio', to='servizi.servizio', verbose_name='Servizio')),
            ],
            options={
                'verbose_name': 'Piano servizio',
                'verbose_name_plural': 'Piani servizio',
                'ordering': ['-anno', 'cliente__ragione_sociale'],
            },
        ),
        migrations.AddField(
            model_name='ods',
            name='piano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ods_set', to='servizi.pianoservizio', verbose_name='Piano'),
        ),
    ]
