# Generated by Django 5.2 on 2026-07-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0022_pianificazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominioods',
            name='latitudine',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='condominioods',
            name='longitudine',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
