# Generated by Django 5.2 on 2026-08-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0023_condominioods_latitudine_condominioods_longitudine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ods',
            name='fatturazione_diversa',
            field=models.BooleanField(default=False, help_text='Da fatturare con altra ragione sociale, a cura del cliente (OS2)', verbose_name='Fatturazione diversa'),
        ),
    ]
