# Generated by Django 5.2 on 2026-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizi', '0024_ods_fatturazione_diversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='distinta',
            name='importo_os2_incassato',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quota di importo_ricevuto proveniente da servizi OS2 (fatturazione esterna), salvata alla chiusura perché le righe OS2 vengono cancellate e non sarebbero più ricostruibili.', max_digits=10, null=True, verbose_name='Di cui OS2'),
        ),
    ]
