# Generated by Django 5.2 on 2026-08-26 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automezzi', '0001_initial'),
        ('servizi', '0027_servizio_non_prevede_consumo_prodotti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinta',
            name='mezzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distinte_mezzo', to='automezzi.automezzo', verbose_name='Mezzo'),
        ),
    ]
