# Generated by Django 5.2 on 2026-05-26 13:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0002_fornitore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineAcquisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordine', models.CharField(blank=True, max_length=50, unique=True)),
                ('data_ordine', models.DateField(default=django.utils.timezone.localdate)),
                ('data_consegna_richiesta', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('inviato', 'Inviato al fornitore'), ('ricevuto_parz', 'Ricevuto parzialmente'), ('ricevuto', 'Ricevuto'), ('fatturato', 'Fatturato'), ('pagato', 'Pagato'), ('annullato', 'Annullato')], default='bozza', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini_acquisto_creati', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini_acquisto', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Ordine di Acquisto',
                'verbose_name_plural': 'Ordini di Acquisto',
                'ordering': ['-data_ordine', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FatturaPassiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fattura', models.CharField(max_length=50)),
                ('data_fattura', models.DateField()),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('imponibile', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5)),
                ('importo_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('totale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('file_fattura', models.FileField(blank=True, null=True, upload_to='fatture_passive/%Y/')),
                ('stato_pagamento', models.CharField(choices=[('da_pagare', 'Da pagare'), ('pagata', 'Pagata'), ('annullata', 'Annullata')], default='da_pagare', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatture_passive_create', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatture_passive', to='anagrafica.fornitore')),
                ('ordini', models.ManyToManyField(blank=True, related_name='fatture', to='acquisti.ordineacquisto', verbose_name='Ordini collegati')),
            ],
            options={
                'verbose_name': 'Fattura Passiva',
                'verbose_name_plural': 'Fatture Passive',
                'ordering': ['-data_fattura'],
            },
        ),
        migrations.CreateModel(
            name='RigaOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(blank=True, help_text='Descrizione articolo (se prodotto non selezionato)', max_length=300)),
                ('unita_misura', models.CharField(blank=True, max_length=20)),
                ('quantita_ordinata', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('quantita_ricevuta', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('prezzo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='acquisti.ordineacquisto')),
            ],
            options={
                'verbose_name': 'Riga Ordine',
                'verbose_name_plural': 'Righe Ordine',
                'ordering': ['pk'],
            },
        ),
    ]
