# Generated by Django 5.2 on 2026-05-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisti', '0001_initial'),
        ('magazzino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigaordine',
            name='prodotto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righe_ordine', to='magazzino.prodotto'),
        ),
        migrations.AlterUniqueTogether(
            name='fatturapassiva',
            unique_together={('fornitore', 'numero_fattura')},
        ),
    ]
