# Generated by Django 5.2 on 2026-05-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisti', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigaordine',
            name='nr_colli',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nr. colli'),
        ),
    ]
