# Generated by Django 5.2 on 2026-05-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisti', '0003_nr_colli_riga_ordine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rigaordine',
            name='nr_colli',
        ),
    ]
