# Generated by Django 5.2 on 2026-05-30 01:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisti', '0004_remove_nr_colli_riga_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigaordine',
            name='aliquota_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5, verbose_name='IVA %'),
        ),
    ]
