# Generated by Django 5.2 on 2026-08-11 16:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisti', '0005_riga_ordine_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatturapassiva',
            name='importo_pagato',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Importo pagato'),
        ),
    ]
