# Generated by Django 5.2 on 2026-05-26 13:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisti', '0001_initial'),
        ('anagrafica', '0002_fornitore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descrizione', models.TextField(blank=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prodotto', models.CharField(max_length=200)),
                ('codice_interno', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('codice_fornitore', models.CharField(blank=True, max_length=50)),
                ('descrizione', models.TextField(blank=True)),
                ('unita_misura', models.CharField(choices=[('pz', 'Pezzo (pz)'), ('conf', 'Confezione'), ('kg', 'Chilogrammo (kg)'), ('gr', 'Grammo (gr)'), ('lt', 'Litro (lt)'), ('ml', 'Millilitro (ml)')], default='pz', max_length=10)),
                ('quantita_per_confezione', models.DecimalField(blank=True, decimal_places=3, help_text='Quantità unitaria contenuta in ogni confezione (es: 1000 esche, 10 lt)', max_digits=10, null=True)),
                ('formato_confezione', models.CharField(blank=True, help_text='Descrizione formato (es: conf. da 1000 esche, tanica 10L)', max_length=100)),
                ('is_biocida', models.BooleanField(default=False, help_text='Il prodotto è un biocida registrato', verbose_name='Biocida')),
                ('principio_attivo', models.CharField(blank=True, max_length=200)),
                ('numero_registrazione', models.CharField(blank=True, help_text='Numero di registrazione ministeriale del biocida', max_length=100)),
                ('attivo', models.BooleanField(default=True)),
                ('note_interne', models.TextField(blank=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='magazzino/prodotti/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodotti', to='magazzino.categoria')),
                ('fornitore_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodotti_magazzino', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['nome_prodotto'],
            },
        ),
        migrations.CreateModel(
            name='Ricezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ddt', models.CharField(blank=True, max_length=50)),
                ('data_ricezione', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricezioni_create', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ricezioni', to='anagrafica.fornitore')),
                ('ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricezioni', to='acquisti.ordineacquisto', verbose_name='ODA di riferimento')),
            ],
            options={
                'verbose_name': 'Ricezione',
                'verbose_name_plural': 'Ricezioni',
                'ordering': ['-data_ricezione', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RigaRicezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_ricevuta', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('prezzo_unitario', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('numero_lotto', models.CharField(blank=True, max_length=100)),
                ('data_scadenza_lotto', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_ricezione', to='magazzino.prodotto')),
                ('ricezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='magazzino.ricezione')),
                ('riga_ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righe_ricezione', to='acquisti.rigaordine', verbose_name='Riga ODA')),
            ],
            options={
                'verbose_name': 'Riga Ricezione',
                'verbose_name_plural': 'Righe Ricezione',
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='prodotto',
            index=models.Index(fields=['codice_interno'], name='magazzino_p_codice__b49450_idx'),
        ),
        migrations.AddIndex(
            model_name='prodotto',
            index=models.Index(fields=['categoria', 'attivo'], name='magazzino_p_categor_32fd99_idx'),
        ),
    ]
