# Generated by Django 5.2 on 2026-05-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='scheda_tecnica',
            field=models.FileField(blank=True, null=True, upload_to='magazzino/schede_tecniche/', verbose_name='Scheda tecnica'),
        ),
    ]
