# Generated by Django 5.2 on 2026-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_scheda_tecnica_prodotto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigaricezione',
            name='nr_colli_oda',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nr. colli ODA'),
        ),
    ]
