# Generated by Django 5.2 on 2026-05-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0003_nr_colli_oda_riga_ricezione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rigaricezione',
            name='nr_colli_oda',
        ),
        migrations.AddField(
            model_name='rigaricezione',
            name='nr_colli',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nr. colli ricevuti'),
        ),
    ]
