# Generated by Django 5.2 on 2026-05-29 09:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cespiti', '0001_initial'),
        ('magazzino', '0004_swap_nr_colli_rigaricezione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaricoMezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carico', 'Carico mezzo'), ('scarico', 'Scarico mezzo')], max_length=10)),
                ('data', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carichi_magazzino', to='cespiti.automezzo')),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carichi_mezzo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carico/Scarico Mezzo',
                'verbose_name_plural': 'Carichi/Scarichi Mezzo',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RigaCaricoMezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=3, max_digits=12)),
                ('carico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='magazzino.caricomezzo')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_carico_mezzo', to='magazzino.prodotto')),
            ],
            options={
                'verbose_name': 'Riga Carico Mezzo',
                'verbose_name_plural': 'Righe Carico Mezzo',
            },
        ),
        migrations.CreateModel(
            name='ScortaMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prodotto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorta', to='magazzino.prodotto')),
            ],
            options={
                'verbose_name': 'Scorta Magazzino',
                'verbose_name_plural': 'Scorte Magazzino',
                'ordering': ['prodotto__nome_prodotto'],
            },
        ),
        migrations.CreateModel(
            name='ScortaMezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorte_magazzino', to='cespiti.automezzo')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorte_mezzo', to='magazzino.prodotto')),
            ],
            options={
                'verbose_name': 'Scorta Mezzo',
                'verbose_name_plural': 'Scorte Mezzo',
                'ordering': ['mezzo', 'prodotto__nome_prodotto'],
                'unique_together': {('mezzo', 'prodotto')},
            },
        ),
    ]
