# Generated by Django 5.2 on 2026-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0005_scorte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caricomezzo',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
