# Generated by Django 5.2 on 2026-05-29 15:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cespiti', '0001_initial'),
        ('magazzino', '0006_carico_data_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caricomezzo',
            name='stabilimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carichi_mezzo', to='cespiti.stabilimento', verbose_name='Stabilimento'),
        ),
        migrations.AddField(
            model_name='ricezione',
            name='stabilimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ricezioni_magazzino', to='cespiti.stabilimento', verbose_name='Stabilimento destinatario'),
        ),
        migrations.CreateModel(
            name='ScortaStabilimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorte_stabilimenti', to='magazzino.prodotto')),
                ('stabilimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorte_prodotti', to='cespiti.stabilimento')),
            ],
            options={
                'verbose_name': 'Scorta Stabilimento',
                'verbose_name_plural': 'Scorte Stabilimenti',
                'ordering': ['stabilimento', 'prodotto__nome_prodotto'],
                'unique_together': {('stabilimento', 'prodotto')},
            },
        ),
        migrations.DeleteModel(
            name='ScortaMagazzino',
        ),
    ]
