# Generated by Django 5.2 on 2026-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0007_stabilimenti_scorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricezione',
            name='bolla_firmata',
            field=models.FileField(blank=True, null=True, upload_to='magazzino/bolle_firmate/', verbose_name='Bolla firmata'),
        ),
    ]
