# Generated by Django 5.2 on 2026-08-26 08:50, mano modificata il 26/08/2026:
# TipoAttrezzatura/AttrezzaturaAutomezzo vengono spostati da cespiti (dove
# le tabelle esistevano gia') senza perdere dati — SeparateDatabaseAndState
# + RunSQL di rinomina, stesso schema di automezzi/migrations/0001_initial.py.
# Le AlterField sulle FK 'mezzo' (gia' tabelle di magazzino) sono invece
# migrazioni normali: Django gestisce da solo la ricostruzione tabella su
# SQLite preservando i dati.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automezzi', '0001_initial'),
        ('magazzino', '0013_consumocisterna'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TipoAttrezzatura',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                        ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                    ],
                    options={
                        'verbose_name': 'Tipo attrezzatura',
                        'verbose_name_plural': 'Tipi attrezzatura',
                        'ordering': ['nome'],
                    },
                ),
                migrations.CreateModel(
                    name='AttrezzaturaAutomezzo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('fissa', models.BooleanField(default=True, verbose_name='Fissa')),
                        ('note', models.TextField(blank=True, verbose_name='Note')),
                        ('automezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrezzature', to='automezzi.automezzo', verbose_name='Automezzo')),
                        ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attrezzature_automezzo', to='magazzino.tipoattrezzatura', verbose_name='Tipo attrezzatura')),
                    ],
                    options={
                        'verbose_name': 'Attrezzatura automezzo',
                        'verbose_name_plural': 'Attrezzature automezzo',
                        'ordering': ['tipo__nome'],
                        'unique_together': {('automezzo', 'tipo')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_tipoattrezzatura RENAME TO magazzino_tipoattrezzatura;",
                    reverse_sql="ALTER TABLE magazzino_tipoattrezzatura RENAME TO cespiti_tipoattrezzatura;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_attrezzaturaautomezzo RENAME TO magazzino_attrezzaturaautomezzo;",
                    reverse_sql="ALTER TABLE magazzino_attrezzaturaautomezzo RENAME TO cespiti_attrezzaturaautomezzo;",
                ),
            ],
        ),
        migrations.AlterField(
            model_name='caricocisterna',
            name='mezzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carichi_cisterna', to='automezzi.automezzo'),
        ),
        migrations.AlterField(
            model_name='caricomezzo',
            name='mezzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carichi_magazzino', to='automezzi.automezzo'),
        ),
        migrations.AlterField(
            model_name='consumocisterna',
            name='mezzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumi_cisterna', to='automezzi.automezzo'),
        ),
        migrations.AlterField(
            model_name='ricezione',
            name='mezzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricezioni_mezzo', to='automezzi.automezzo', verbose_name='Mezzo destinatario'),
        ),
        migrations.AlterField(
            model_name='scortamezzo',
            name='mezzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorte_magazzino', to='automezzi.automezzo'),
        ),
    ]
