# Generated by Django 5.2 on 2026-08-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0014_tipoattrezzatura_alter_caricocisterna_mezzo_and_more'),
        ('stabilimenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caricomezzo',
            name='stabilimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carichi_mezzo', to='stabilimenti.stabilimento', verbose_name='Stabilimento'),
        ),
        migrations.AlterField(
            model_name='ricezione',
            name='stabilimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ricezioni_magazzino', to='stabilimenti.stabilimento', verbose_name='Stabilimento destinatario'),
        ),
        migrations.AlterField(
            model_name='scortastabilimento',
            name='stabilimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorte_prodotti', to='stabilimenti.stabilimento'),
        ),
    ]
