# Generated by Django 5.2 on 2026-09-16 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0015_alter_caricomezzo_stabilimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumocisterna',
            name='prodotto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumi_cisterna', to='magazzino.prodotto', verbose_name='Prodotto (solo per rapportino)'),
        ),
    ]
