# Generated by Django 5.2 on 2026-06-24 07:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0008_sede_unica'),
        ('magazzino', '0010_ricezione_mezzo'),
        ('servizi', '0021_add_richiede_installazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numero')),
                ('data_installazione', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data installazione')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installazioni_create', to=settings.AUTH_USER_MODEL)),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installazioni', to='anagrafica.filiale', verbose_name='Sede cliente')),
                ('privato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installazioni', to='anagrafica.privato', verbose_name='Cliente privato')),
                ('prodotto_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installazioni', to='magazzino.prodotto', verbose_name='Prodotto principale')),
                ('servizio', models.ForeignKey(limit_choices_to={'richiede_installazione': True}, on_delete=django.db.models.deletion.PROTECT, related_name='installazioni', to='servizi.servizio', verbose_name='Tipo installazione')),
            ],
            options={
                'verbose_name': 'Installazione',
                'verbose_name_plural': 'Installazioni',
                'ordering': ['-data_installazione', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventoInstallazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_intervento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data intervento')),
                ('quantita_prodotto', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Quantità prodotto')),
                ('note', models.TextField(blank=True, verbose_name='Note intervento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventi_installazioni_creati', to=settings.AUTH_USER_MODEL)),
                ('installazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='installazioni.installazione', verbose_name='Installazione')),
                ('ods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventi_installazioni', to='servizi.ods', verbose_name='ODS collegato')),
                ('prodotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventi_installazioni', to='magazzino.prodotto', verbose_name='Prodotto usato')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventi_installazioni', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico')),
            ],
            options={
                'verbose_name': 'Intervento',
                'verbose_name_plural': 'Interventi',
                'ordering': ['-data_intervento', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Postazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Lascia vuoto: verrà assegnato automaticamente in sequenza', verbose_name='N° postazione')),
                ('descrizione_luogo', models.TextField(blank=True, help_text="Descrivi la posizione esatta (es. 'angolo nord-est magazzino, vicino al bancale B')", verbose_name='Descrizione luogo')),
                ('ha_cartello', models.BooleanField(default=True, help_text='Deseleziona se non è possibile apporre un cartello segnaletico', verbose_name='Ha cartello')),
                ('numero_cartello', models.CharField(blank=True, help_text='Numero/codice del cartello segnaletico applicato', max_length=50, verbose_name='N° cartello')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postazioni', to='installazioni.installazione', verbose_name='Installazione')),
            ],
            options={
                'verbose_name': 'Postazione',
                'verbose_name_plural': 'Postazioni',
                'ordering': ['numero'],
                'unique_together': {('installazione', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RiscontroPostazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esito', models.CharField(choices=[('vuota', 'Vuota / nessuna attività'), ('innescata', 'Innescata / esca consumata'), ('roditori', 'Roditori trovati'), ('insetti', 'Insetti trovati'), ('danneggiata', 'Postazione danneggiata'), ('assente', 'Postazione assente / non trovata')], max_length=20, verbose_name='Esito')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Note')),
                ('intervento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscontri', to='installazioni.interventoinstallazione', verbose_name='Intervento')),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscontri', to='installazioni.postazione', verbose_name='Postazione')),
            ],
            options={
                'verbose_name': 'Riscontro postazione',
                'verbose_name_plural': 'Riscontri postazione',
                'ordering': ['postazione__numero'],
                'unique_together': {('intervento', 'postazione')},
            },
        ),
    ]
