# Generated by Django 5.2 on 2026-06-24 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installazioni', '0001_initial'),
        ('magazzino', '0010_ricezione_mezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postazione',
            name='prodotto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postazioni', to='magazzino.prodotto', verbose_name='Prodotto'),
        ),
        migrations.AddField(
            model_name='postazione',
            name='quantita',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Quantità'),
        ),
    ]
