# Generated by Django 5.2 on 2026-06-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installazioni', '0002_postazione_prodotto'),
        ('servizi', '0021_add_richiede_installazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='installazione',
            name='ods_creato',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installazione_collegata', to='servizi.ods', verbose_name='ODS creato'),
        ),
    ]
