# Generated by Django 5.2 on 2026-07-10 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installazioni', '0003_ods_creato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postazione',
            name='pos_x',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentuale orizzontale sulla planimetria (0-100)', max_digits=5, null=True, verbose_name='Posizione X (%)'),
        ),
        migrations.AddField(
            model_name='postazione',
            name='pos_y',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentuale verticale sulla planimetria (0-100)', max_digits=5, null=True, verbose_name='Posizione Y (%)'),
        ),
        migrations.CreateModel(
            name='Planimetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, help_text="Es. 'Piano terra', 'Magazzino', 'Cucina'", max_length=100, verbose_name='Titolo')),
                ('immagine', models.ImageField(upload_to='planimetrie/%Y/%m/', verbose_name='Immagine planimetria')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planimetrie_create', to=settings.AUTH_USER_MODEL)),
                ('installazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planimetrie', to='installazioni.installazione', verbose_name='Installazione')),
            ],
            options={
                'verbose_name': 'Planimetria',
                'verbose_name_plural': 'Planimetrie',
                'ordering': ['titolo', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='postazione',
            name='planimetria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postazioni', to='installazioni.planimetria', verbose_name='Planimetria'),
        ),
    ]
