# Generated by Django 5.2 on 2026-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installazioni', '0004_postazione_pos_x_postazione_pos_y_planimetria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planimetria',
            name='immagine',
            field=models.FileField(help_text='JPG, PNG o HEIC (foto da smartphone)', upload_to='planimetrie/%Y/%m/', verbose_name='Immagine planimetria'),
        ),
    ]
