# Generated by Django 5.2 on 2026-07-12 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installazioni', '0005_alter_planimetria_immagine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installazione',
            name='chiusa_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installazioni_chiuse', to=settings.AUTH_USER_MODEL, verbose_name='Chiusa da'),
        ),
        migrations.AddField(
            model_name='installazione',
            name='data_completamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data completamento'),
        ),
        migrations.AddField(
            model_name='installazione',
            name='stato',
            field=models.CharField(choices=[('in_corso', 'In corso'), ('completata', 'Completata')], default='in_corso', max_length=20, verbose_name='Stato'),
        ),
    ]
