# Generated by Django 5.2 on 2026-08-26 09:35, mano modificata il 26/08/2026:
# spostamento di un modello Django tra due app senza perdere dati, stesso
# schema di automezzi/migrations/0001_initial.py dello stesso giorno.

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0009_filiale_latitudine_filiale_longitudine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cespiti', '0003_remove_automezzi_cluster'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Stabilimento',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(max_length=200)),
                        ('codice_stabilimento', models.CharField(max_length=10, unique=True)),
                        ('indirizzo', models.CharField(max_length=300)),
                        ('cap', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Il CAP deve essere di 5 cifre', regex='^\\d{5}$')])),
                        ('citta', models.CharField(max_length=100)),
                        ('provincia', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Provincia: 2 lettere maiuscole', regex='^[A-Z]{2}$')])),
                        ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                        ('email_filiale', models.EmailField(blank=True, max_length=254, null=True)),
                        ('superficie_mq', models.PositiveIntegerField(blank=True, null=True)),
                        ('numero_piani', models.PositiveSmallIntegerField(default=1)),
                        ('anno_costruzione', models.PositiveSmallIntegerField(blank=True, null=True)),
                        ('attivo', models.BooleanField(default=True)),
                        ('data_apertura', models.DateField(blank=True, null=True)),
                        ('data_chiusura', models.DateField(blank=True, null=True)),
                        ('note_generali', models.TextField(blank=True, null=True)),
                        ('data_creazione', models.DateTimeField(auto_now_add=True)),
                        ('data_modifica', models.DateTimeField(auto_now=True)),
                        ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stabilimenti_stabilimenti_creati', to=settings.AUTH_USER_MODEL)),
                        ('modificato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stabilimenti_stabilimenti_modificati', to=settings.AUTH_USER_MODEL)),
                        ('responsabile_amministrativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stabilimenti_stabilimenti_amministrativi', to=settings.AUTH_USER_MODEL)),
                        ('responsabile_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stabilimenti_stabilimenti_operativi', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Stabilimento',
                        'verbose_name_plural': 'Stabilimenti',
                        'ordering': ['nome'],
                    },
                ),
                migrations.CreateModel(
                    name='DocStabilimento',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome_documento', models.CharField(max_length=200)),
                        ('tipo_documento', models.CharField(choices=[('scia', 'SCIA'), ('autorizzazione', 'Autorizzazione Edilizia'), ('permesso_costruire', 'Permesso di Costruire'), ('contratto_derattizzazione', 'Contratto Derattizzazione'), ('contratto_disinfestazione', 'Contratto Disinfestazione'), ('contratto_pulizie', 'Contratto Pulizie'), ('contratto_vigilanza', 'Contratto Vigilanza'), ('contratto_manutenzione', 'Contratto Manutenzione'), ('cert_prevenzione_incendi', 'Certificato Prevenzione Incendi'), ('cert_agibilita', 'Certificato di Agibilità'), ('cert_conformita', 'Certificato di Conformità'), ('collaudo_impianti', 'Collaudo Impianti'), ('verifica_ascensori', 'Verifica Ascensori'), ('controllo_caldaie', 'Controllo Caldaie'), ('controllo_antincendio', 'Controllo Antincendio'), ('planimetria', 'Planimetria'), ('verbale', 'Verbale Controllo'), ('contratto', 'Contratto Generico'), ('certificazione', 'Certificazione Generica'), ('altro', 'Altro')], default='altro', max_length=30)),
                        ('versione', models.CharField(default='1.0', max_length=10)),
                        ('descrizione', models.TextField(blank=True, null=True)),
                        ('file_documento', models.FileField(upload_to='stabilimenti/documenti/%Y/%m/')),
                        ('data_documento', models.DateField(blank=True, null=True)),
                        ('data_scadenza', models.DateField(blank=True, null=True)),
                        ('attivo', models.BooleanField(default=True)),
                        ('note', models.TextField(blank=True, null=True)),
                        ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                        ('data_modifica', models.DateTimeField(auto_now=True)),
                        ('caricato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stabilimenti_documenti_caricati', to=settings.AUTH_USER_MODEL)),
                        ('stabilimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='stabilimenti.stabilimento')),
                    ],
                    options={
                        'verbose_name': 'Documento Stabilimento',
                        'verbose_name_plural': 'Documenti Stabilimenti',
                        'ordering': ['-data_inserimento'],
                    },
                ),
                migrations.CreateModel(
                    name='CostiStabilimento',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('numero_pratica', models.CharField(max_length=50, unique=True)),
                        ('causale', models.CharField(choices=[('manutenzione_ordinaria', 'Manutenzione Ordinaria'), ('manutenzione_straordinaria', 'Manutenzione Straordinaria'), ('adeguamento', 'Adeguamento Strutturale'), ('servizi_periodici', 'Servizi Periodici'), ('certificazioni', 'Certificazioni Obbligatorie'), ('energia_elettrica', 'Energia Elettrica'), ('gas_naturale', 'Gas Naturale'), ('acqua', 'Acqua e Scarichi'), ('telefonia', 'Telefonia e Internet'), ('rifiuti', 'Smaltimento Rifiuti'), ('sicurezza', 'Sicurezza e Vigilanza'), ('pulizie', 'Servizi di Pulizia'), ('assicurazioni', 'Assicurazioni'), ('tasse', 'Tasse e Tributi'), ('altro', 'Altro')], default='servizi_periodici', max_length=50)),
                        ('stato', models.CharField(choices=[('preventivo', 'Preventivo'), ('approvato', 'Approvato'), ('in_corso', 'In Corso'), ('completato', 'Completato'), ('fatturato', 'Fatturato'), ('pagato', 'Pagato')], default='preventivo', max_length=20)),
                        ('titolo', models.CharField(max_length=200)),
                        ('descrizione', models.TextField()),
                        ('importo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                        ('iva_percentuale', models.DecimalField(decimal_places=2, default=22, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                        ('data_richiesta', models.DateField(default=django.utils.timezone.now)),
                        ('data_inizio_lavori', models.DateField(blank=True, null=True)),
                        ('data_fine_lavori', models.DateField(blank=True, null=True)),
                        ('data_fattura', models.DateField(blank=True, null=True)),
                        ('data_scadenza_servizio', models.DateField(blank=True, null=True, verbose_name='Prossima Scadenza')),
                        ('fattura', models.FileField(blank=True, null=True, upload_to='stabilimenti/fatture/%Y/%m/')),
                        ('preventivo', models.FileField(blank=True, null=True, upload_to='stabilimenti/preventivi/%Y/%m/')),
                        ('certificato', models.FileField(blank=True, null=True, upload_to='stabilimenti/certificati/%Y/%m/')),
                        ('allegato1', models.FileField(blank=True, null=True, upload_to='stabilimenti/allegati/%Y/%m/')),
                        ('allegato2', models.FileField(blank=True, null=True, upload_to='stabilimenti/allegati/%Y/%m/')),
                        ('note_interne', models.TextField(blank=True, null=True)),
                        ('data_creazione', models.DateTimeField(auto_now_add=True)),
                        ('data_modifica', models.DateTimeField(auto_now=True)),
                        ('consumo_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                        ('consumo_mc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                        ('periodo_fatturazione_da', models.DateField(blank=True, null=True)),
                        ('periodo_fatturazione_a', models.DateField(blank=True, null=True)),
                        ('codice_pdr_pod', models.CharField(blank=True, max_length=50, null=True)),
                        ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stabilimenti_costi_stabilimenti', to='anagrafica.fornitore')),
                        ('incaricato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stabilimenti_costi_gestiti', to=settings.AUTH_USER_MODEL)),
                        ('stabilimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costi', to='stabilimenti.stabilimento')),
                    ],
                    options={
                        'verbose_name': 'Costo Stabilimento',
                        'verbose_name_plural': 'Costi Stabilimenti',
                        'ordering': ['-data_creazione'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_stabilimento RENAME TO stabilimenti_stabilimento;",
                    reverse_sql="ALTER TABLE stabilimenti_stabilimento RENAME TO cespiti_stabilimento;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_docstabilimento RENAME TO stabilimenti_docstabilimento;",
                    reverse_sql="ALTER TABLE stabilimenti_docstabilimento RENAME TO cespiti_docstabilimento;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE cespiti_costistabilimento RENAME TO stabilimenti_costistabilimento;",
                    reverse_sql="ALTER TABLE stabilimenti_costistabilimento RENAME TO cespiti_costistabilimento;",
                ),
            ],
        ),
    ]
