# Generated by Django 5.2 on 2026-08-26 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WABroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attivo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data cancellazione')),
                ('titolo', models.CharField(max_length=200)),
                ('messaggio', models.TextField()),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('in_corso', 'In corso'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='bozza', max_length=12)),
                ('avviato_at', models.DateTimeField(blank=True, null=True)),
                ('completato_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Broadcast WhatsApp',
                'verbose_name_plural': 'Broadcast WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WABroadcastDestinatario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attivo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data cancellazione')),
                ('numero', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('stato', models.CharField(choices=[('pending', 'In attesa'), ('sent', 'Inviato'), ('failed', 'Fallito'), ('skipped', 'Saltato')], default='pending', max_length=10)),
                ('errore', models.CharField(blank=True, max_length=500)),
                ('inviato_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatari', to='whatsapp.wabroadcast')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Destinatario broadcast',
                'verbose_name_plural': 'Destinatari broadcast',
            },
        ),
        migrations.CreateModel(
            name='WAConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attivo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data cancellazione')),
                ('numero_mittente', models.CharField(blank=True, help_text='Numero WhatsApp del mittente (es: 393331234567)', max_length=20)),
                ('foto_profilo', models.ImageField(blank=True, help_text='Foto profilo da impostare su WhatsApp', null=True, upload_to='whatsapp/profilo/')),
                ('stato_wa', models.CharField(blank=True, help_text="Testo 'Informazioni' del profilo WhatsApp (max 139 caratteri)", max_length=139, verbose_name='Stato / About')),
                ('delay_min', models.PositiveIntegerField(default=8, help_text='Attesa minima tra un messaggio e il successivo', verbose_name='Delay minimo (sec)')),
                ('delay_max', models.PositiveIntegerField(default=20, help_text='Attesa massima tra un messaggio e il successivo', verbose_name='Delay massimo (sec)')),
                ('attivo', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Configurazione WhatsApp',
                'verbose_name_plural': 'Configurazione WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WAMessaggio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modifica')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attivo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data cancellazione')),
                ('destinatario_numero', models.CharField(max_length=20)),
                ('destinatario_nome', models.CharField(blank=True, max_length=200)),
                ('testo', models.TextField()),
                ('stato', models.CharField(choices=[('pending', 'In attesa'), ('sent', 'Inviato'), ('failed', 'Fallito')], default='pending', max_length=10)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornitore', 'Fornitore'), ('manuale', 'Manuale'), ('broadcast', 'Broadcast')], default='manuale', max_length=12)),
                ('errore', models.TextField(blank=True)),
                ('inviato_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Messaggio WhatsApp',
                'verbose_name_plural': 'Messaggi WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
