# Generated by Django 5.2 on 2026-05-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=200, verbose_name='Ragione Sociale')),
                ('indirizzo', models.CharField(max_length=200, verbose_name='Indirizzo Sede Legale')),
                ('citta', models.CharField(max_length=100, verbose_name='Città')),
                ('cap', models.CharField(max_length=5, verbose_name='CAP')),
                ('provincia', models.CharField(blank=True, max_length=5, verbose_name='Provincia')),
                ('partita_iva', models.CharField(max_length=15, verbose_name='Partita IVA')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale')),
                ('codice_univoco', models.CharField(blank=True, max_length=7, verbose_name='Codice Univoco SDI')),
                ('pec', models.EmailField(max_length=254, verbose_name='PEC')),
                ('referente', models.CharField(blank=True, max_length=200, verbose_name='Referente Principale')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email_direzione', models.EmailField(blank=True, help_text='Per contratti e comunicazioni direzionali', max_length=254, verbose_name='Email Direzione')),
                ('email_amministrazione', models.EmailField(blank=True, help_text='Per fatture e pagamenti', max_length=254, verbose_name='Email Amministrazione')),
                ('email_operativo', models.EmailField(help_text='Per pianificazione interventi e rapporti', max_length=254, verbose_name='Email Operativo')),
                ('email_operativo_2', models.EmailField(blank=True, help_text='Contatto operativo aggiuntivo', max_length=254, verbose_name='Email Operativo 2')),
                ('tipo_pagamento', models.CharField(choices=[('immediato', 'Immediato'), ('30_gg', '30 gg d.f.'), ('60_gg', '60 gg d.f.'), ('90_gg', '90 gg d.f.'), ('120_gg', '120 gg d.f.')], default='immediato', max_length=20, verbose_name='Modalità Pagamento')),
                ('installato', models.BooleanField(default=False, help_text='Tutte le stazioni sono state installate', verbose_name='Installazione Completata')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['ragione_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Filiale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Sede / Punto Vendita')),
                ('tipo_sede', models.CharField(choices=[('punto_vendita', 'Punto Vendita'), ('magazzino', 'Magazzino'), ('ufficio', 'Ufficio'), ('deposito', 'Deposito'), ('laboratorio', 'Laboratorio'), ('altro', 'Altro')], default='punto_vendita', max_length=20, verbose_name='Tipo Sede')),
                ('indirizzo', models.CharField(max_length=200, verbose_name='Indirizzo')),
                ('citta', models.CharField(max_length=100, verbose_name='Città')),
                ('cap', models.CharField(max_length=5, verbose_name='CAP')),
                ('provincia', models.CharField(blank=True, max_length=5, verbose_name='Provincia')),
                ('regione', models.CharField(blank=True, max_length=100, verbose_name='Regione')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('referente_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome Referente')),
                ('referente_tel', models.CharField(blank=True, max_length=20, verbose_name='Tel. Referente')),
                ('referente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Referente')),
                ('orario_apertura', models.CharField(blank=True, help_text='Es: 08:00-20:00 / Lun-Sab', max_length=100, verbose_name='Orario Apertura')),
                ('giorno_chiusura', models.CharField(blank=True, choices=[('', 'Nessun giorno di chiusura'), ('lunedi', 'Lunedì'), ('martedi', 'Martedì'), ('mercoledi', 'Mercoledì'), ('giovedi', 'Giovedì'), ('venerdi', 'Venerdì'), ('sabato', 'Sabato'), ('domenica', 'Domenica')], default='', max_length=20, verbose_name='Giorno di Chiusura')),
                ('note_accesso', models.TextField(blank=True, help_text='Istruzioni per accedere alla sede (citofono, portone, ecc.)', verbose_name='Note Accesso')),
                ('installato', models.BooleanField(default=False, verbose_name='Installazione Completata')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiali', to='anagrafica.azienda', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Filiale / Sede',
                'verbose_name_plural': 'Filiali / Sedi',
                'ordering': ['cliente__ragione_sociale', 'nome'],
            },
        ),
    ]
