# Generated by Django 5.2 on 2026-05-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=200, verbose_name='Ragione Sociale')),
                ('indirizzo', models.CharField(blank=True, max_length=200, verbose_name='Indirizzo')),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('cap', models.CharField(blank=True, max_length=5, verbose_name='CAP')),
                ('provincia', models.CharField(blank=True, max_length=5, verbose_name='Provincia')),
                ('regione', models.CharField(blank=True, max_length=100, verbose_name='Regione')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('partita_iva', models.CharField(max_length=15, verbose_name='Partita IVA')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale')),
                ('pec', models.EmailField(blank=True, max_length=254, verbose_name='PEC')),
                ('codice_destinatario', models.CharField(blank=True, max_length=7, verbose_name='Codice SDI')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('categoria', models.CharField(choices=[('materie_prime', 'Materie Prime'), ('semilavorati', 'Semilavorati'), ('servizi', 'Servizi'), ('consulenza', 'Consulenza'), ('software', 'Software/IT'), ('trasporti', 'Trasporti e Logistica'), ('altri', 'Altri')], default='altri', max_length=20, verbose_name='Categoria')),
                ('tipo_pagamento', models.CharField(choices=[('bonifico_30', 'Bonifico 30 gg'), ('bonifico_60', 'Bonifico 60 gg'), ('bonifico_90', 'Bonifico 90 gg'), ('bonifico_120', 'Bonifico 120 gg'), ('rid_30', 'RID 30 gg'), ('rid_60', 'RID 60 gg'), ('riba_30', 'RIBA 30 gg'), ('riba_60', 'RIBA 60 gg'), ('contrassegno', 'Contrassegno'), ('anticipo', 'Anticipo 100%'), ('fine_mese', 'Fine Mese'), ('immediato', 'Pagamento Immediato')], default='bonifico_30', max_length=20, verbose_name='Tipo Pagamento')),
                ('priorita_pagamento', models.CharField(choices=[('critica', 'Critica (Urgente)'), ('alta', 'Alta (Prioritaria)'), ('media', 'Media (Normale)'), ('bassa', 'Bassa (Differibile)')], default='media', max_length=10, verbose_name='Priorità Pagamento')),
                ('referente_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome Referente')),
                ('referente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Tel. Referente')),
                ('referente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Referente')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'ordering': ['ragione_sociale'],
            },
        ),
    ]
