# Generated by Django 5.2 on 2026-06-14 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0006_azienda_marchio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='portal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_portale', to=settings.AUTH_USER_MODEL, verbose_name='Utente portale cliente'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='utente_riferimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti_in_gestione', to=settings.AUTH_USER_MODEL, verbose_name='Utente interno di riferimento'),
        ),
    ]
