# Generated by Django 5.2 on 2026-06-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0007_azienda_portal_user_azienda_utente_riferimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='sede_unica',
            field=models.BooleanField(default=True, help_text='Il cliente ha un unico luogo di servizio coincidente con questo indirizzo. Non è necessario inserire filiali separate.', verbose_name='Sede unica'),
        ),
    ]
