# Generated by Django 5.2 on 2026-06-16 03:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servizi', '0019_ods_stato_fatturato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveSmallIntegerField(verbose_name='Anno')),
                ('progressivo', models.PositiveIntegerField(verbose_name='Progressivo')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numero fattura')),
                ('data_emissione', models.DateField(verbose_name='Data emissione')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data pagamento')),
                ('stato', models.CharField(choices=[('emessa', 'Emessa'), ('pagata', 'Pagata'), ('annullata', 'Annullata')], default='emessa', max_length=12, verbose_name='Stato')),
                ('dest_nome', models.CharField(max_length=300, verbose_name='Destinatario')),
                ('dest_indirizzo', models.CharField(blank=True, max_length=300)),
                ('dest_cap', models.CharField(blank=True, max_length=10)),
                ('dest_citta', models.CharField(blank=True, max_length=100)),
                ('dest_provincia', models.CharField(blank=True, max_length=5)),
                ('dest_partita_iva', models.CharField(blank=True, max_length=20)),
                ('dest_codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('dest_pec', models.EmailField(blank=True, max_length=254)),
                ('dest_codice_univoco', models.CharField(blank=True, max_length=7)),
                ('emit_ragione_sociale', models.CharField(blank=True, max_length=300)),
                ('emit_indirizzo', models.CharField(blank=True, max_length=300)),
                ('emit_cap_citta', models.CharField(blank=True, max_length=200)),
                ('emit_partita_iva', models.CharField(blank=True, max_length=20)),
                ('emit_codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('emit_telefono', models.CharField(blank=True, max_length=30)),
                ('emit_email', models.EmailField(blank=True, max_length=254)),
                ('emit_iban', models.CharField(blank=True, max_length=40)),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5, verbose_name='Aliquota IVA %')),
                ('imponibile', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Imponibile')),
                ('importo_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA')),
                ('totale', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Totale')),
                ('note_pagamento', models.TextField(blank=True, verbose_name='Condizioni di pagamento')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emessa_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatture_emesse', to=settings.AUTH_USER_MODEL, verbose_name='Emessa da')),
                ('ods', models.ManyToManyField(blank=True, related_name='fatture', to='servizi.ods', verbose_name='ODS collegati')),
            ],
            options={
                'verbose_name': 'Fattura',
                'verbose_name_plural': 'Fatture',
                'ordering': ['-anno', '-progressivo'],
                'unique_together': {('anno', 'progressivo')},
            },
        ),
        migrations.CreateModel(
            name='RigaFattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ods_numero', models.CharField(max_length=20, verbose_name='N° ODS')),
                ('data_servizio', models.DateField(verbose_name='Data servizio')),
                ('descrizione', models.CharField(max_length=300, verbose_name='Descrizione')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo')),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='fatturazione_attiva.fattura', verbose_name='Fattura')),
            ],
            options={
                'verbose_name': 'Riga fattura',
                'verbose_name_plural': 'Righe fattura',
                'ordering': ['data_servizio', 'pk'],
            },
        ),
    ]
