# Generated by Django 5.2 on 2026-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione_attiva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='data_ultimo_sollecito',
            field=models.DateField(blank=True, null=True, verbose_name='Ultimo sollecito'),
        ),
    ]
