# Generated by Django 5.2 on 2026-06-22 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione_attiva', '0002_fattura_data_ultimo_sollecito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveSmallIntegerField(verbose_name='Anno')),
                ('progressivo', models.PositiveIntegerField(verbose_name='Progressivo')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numero NC')),
                ('data_emissione', models.DateField(verbose_name='Data emissione')),
                ('tipo', models.CharField(choices=[('totale', 'Totale'), ('parziale', 'Parziale')], max_length=10, verbose_name='Tipo')),
                ('aliquota_iva', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aliquota IVA %')),
                ('imponibile', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Imponibile')),
                ('importo_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA')),
                ('totale', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Totale')),
                ('descrizione_riga', models.CharField(max_length=500, verbose_name='Descrizione riga')),
                ('note', models.TextField(blank=True, verbose_name='Note / Motivo')),
                ('dest_nome', models.CharField(max_length=300)),
                ('dest_indirizzo', models.CharField(blank=True, max_length=300)),
                ('dest_cap', models.CharField(blank=True, max_length=10)),
                ('dest_citta', models.CharField(blank=True, max_length=100)),
                ('dest_provincia', models.CharField(blank=True, max_length=5)),
                ('dest_partita_iva', models.CharField(blank=True, max_length=20)),
                ('dest_codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('dest_pec', models.EmailField(blank=True, max_length=254)),
                ('dest_codice_univoco', models.CharField(blank=True, max_length=7)),
                ('emit_ragione_sociale', models.CharField(blank=True, max_length=300)),
                ('emit_indirizzo', models.CharField(blank=True, max_length=300)),
                ('emit_cap_citta', models.CharField(blank=True, max_length=200)),
                ('emit_partita_iva', models.CharField(blank=True, max_length=20)),
                ('emit_codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('emit_telefono', models.CharField(blank=True, max_length=30)),
                ('emit_email', models.EmailField(blank=True, max_length=254)),
                ('emit_iban', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emessa_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_credito_emesse', to=settings.AUTH_USER_MODEL, verbose_name='Emessa da')),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_credito', to='fatturazione_attiva.fattura', verbose_name='Fattura di riferimento')),
            ],
            options={
                'verbose_name': 'Nota di credito',
                'verbose_name_plural': 'Note di credito',
                'ordering': ['-anno', '-progressivo'],
                'unique_together': {('anno', 'progressivo')},
            },
        ),
    ]
