# Generated by Django 5.2 on 2026-08-10 13:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione_attiva', '0003_notacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='importo_incassato',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Importo incassato'),
        ),
    ]
