# Generated by Django 5.2 on 2026-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione_attiva', '0005_incassato_fatture_pagate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='compensata',
            field=models.BooleanField(default=False, verbose_name='Compensata in un incasso'),
        ),
    ]
