# Generated by Django 5.2 on 2026-05-13 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('direct', 'Diretta'), ('group', 'Gruppo')], default='direct', max_length=10, verbose_name='Tipo')),
                ('titolo', models.CharField(blank=True, max_length=200, verbose_name='Titolo')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creata_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversazioni_create', to=settings.AUTH_USER_MODEL, verbose_name='Creata da')),
                ('partecipanti', models.ManyToManyField(related_name='chat_conversazioni', to=settings.AUTH_USER_MODEL, verbose_name='Partecipanti')),
            ],
            options={
                'verbose_name': 'Conversazione',
                'verbose_name_plural': 'Conversazioni',
                'db_table': 'comunicazioni_chat_conversazione',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField(verbose_name='Messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi', to='comunicazioni.chatconversazione')),
                ('letto_da', models.ManyToManyField(blank=True, related_name='messaggi_letti', to=settings.AUTH_USER_MODEL)),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_inviati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messaggio',
                'verbose_name_plural': 'Messaggi',
                'db_table': 'comunicazioni_chat_messaggio',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('priorita', models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Priorità')),
                ('stato', models.CharField(choices=[('pending', 'In attesa'), ('in_corso', 'In corso'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='pending', max_length=15, verbose_name='Stato')),
                ('data_scadenza', models.DateTimeField(blank=True, null=True, verbose_name='Data scadenza')),
                ('completato_il', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promemoria_assegnati', to=settings.AUTH_USER_MODEL, verbose_name='Assegnato a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promemoria', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
            ],
            options={
                'verbose_name': 'Promemoria',
                'verbose_name_plural': 'Promemoria',
                'db_table': 'comunicazioni_promemoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'stato'], name='comunicazio_user_id_adc00f_idx'), models.Index(fields=['data_scadenza'], name='comunicazio_data_sc_175129_idx')],
            },
        ),
    ]
