# Generated by Django 5.2 on 2026-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicazioni', '0002_promemoria_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='promemoria',
            name='allegato',
            field=models.FileField(blank=True, help_text='Viene eliminato definitivamente insieme al promemoria', null=True, upload_to='promemoria/allegati/%Y/%m/', verbose_name='Allegato'),
        ),
    ]
